---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/instance: argocd
  app.kubernetes.io/part-of: argocd
  app.kubernetes.io/managed-by: argocd

commonAnnotations:
  argocd.argoproj.io/hook: PreSync
  argocd.argoproj.io/sync-wave: "1"

resources:
  - system-core.yaml
  - managed-services.yaml
