external-dns:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::149745434630:role/cne-dev-jhv3-blue-external-dns-irsa
  extraArgs:
    - '--annotation-filter=vertexinc.com/dns-zone in (private)'
    - '--aws-zone-type=private'
    - '--zone-id-filter=Z09555521T6TE5WXR2IX0'
    - '--zone-id-filter=Z0243034EFQ5QGU0UOPJ'
  zoneNameFilters:
    - platdev.vtxdev.net
