apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metrics-server
  labels:
    templateType: managed-service
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
          - git: 
              repoURL: https://github.com/jharlow1/argocd-jason.git 
              revision: '{{ metadata.labels.vertexinc.com/revision }}'
              files:
                - path: "clusters/{{ name }}/managed-services/metrics-server/config.yaml"
  template:
    metadata:
      name: "{{ path.basename }}-{{ name }}"
      labels:
        app.kubernetes.io/name: "{{ path.basename }}-{{ name }}"
      namespace: argocd
    spec:
      ignoreDifferences:
        - group: argoproj.io
          jsonPointers:
            - /status
          kind: Application
      project: managed-services
      destination:
        server: "{{ server }}"
        namespace: "{{ path.basename }}"
      source: 
        chart: umbrella-metrics-server
        repoURL: https://github.com/jharlow1/argocd-jason.git
        targetRevision: "{{ metadata.labels.vertexinc.com/revision }}"
        path: charts/umbrella-metrics-server
        helm:
          valueFiles:
            - values.yaml
            - values-{{ name }}.yaml
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
