---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/instance: argocd
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/part-of: argocd

commonAnnotations:
  argocd.argoproj.io/sync-wave: "30"

namespace: argocd

# Include all projects.  All apps in all projects will generate an
# ApplicationSet that will only generate Applications for matching
# <cluster_name> + <tenant> + <app_name> combinations.
#
# An ApplicationSet that doesn't match anything will still be configured
# in ArgoCD but won't generate any Application objects & thus not deploy
# the application anywhere. 
resources:
  - metrics-server
  - reloader
  - external-dns-private
  - external-dns-public